<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Obligor Rating_mat-mdc-button-touch-target</name>
   <tag></tag>
   <elementGuidId>31a6beed-61bf-46b7-ac3e-c7a07e4c25b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='createAssessment']/span[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#createAssessment > span.mat-mdc-button-touch-target</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#createAssessment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f420b52b-dfe0-4826-83a5-9a750d63192d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-button-touch-target</value>
      <webElementGuid>b308f311-9643-4448-9aaa-efe360a5af86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createAssessment&quot;)/span[@class=&quot;mat-mdc-button-touch-target&quot;]</value>
      <webElementGuid>a3a55877-15bb-4c02-8c5b-d1b31aa4eae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='createAssessment']/span[4]</value>
      <webElementGuid>9407590d-71ac-4faa-9fb2-7cac4ab029c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]</value>
      <webElementGuid>7c3a568e-0235-4d94-8efa-8a8573a5e8d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
