<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_General Reports_mat-icon notransla_1b9d0d</name>
   <tag></tag>
   <elementGuidId>5405a880-712d-457e-bfde-72d5142009ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parentNode-Detailed > mat-icon.mat-icon.notranslate.icon.fis-icon-sm.fisfont.fis-icon-chevron.fis-icon-rotate-270.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='parentNode-Detailed']/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#parentNode-Detailed</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>67a39d5a-8191-4831-8321-23dea21a1ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>9515424f-7fbe-4f64-80db-c9bc66d88cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fisicon</name>
      <type>Main</type>
      <value>chevron</value>
      <webElementGuid>2c5f491a-6526-420a-9953-7d738bc21f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ruficonstyle</name>
      <type>Main</type>
      <value>rotate-270</value>
      <webElementGuid>0b64f7bb-dae9-4279-ab81-99ac7f97de1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate icon fis-icon-sm fisfont fis-icon-chevron fis-icon-rotate-270 mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>7d4de1c9-ce13-4479-9a2f-15b9f21b18da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c60a2262-a1bb-4129-b475-76fabc6e9958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>b169b3d0-ae56-4739-9c3f-94b1e84953cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>fis-icon-chevron</value>
      <webElementGuid>265e6e7b-169d-4398-a19a-46fa1fdab205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-namespace</name>
      <type>Main</type>
      <value>fisfont</value>
      <webElementGuid>459197dc-889d-4558-a16a-d7e3b5c7710f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fonticon</name>
      <type>Main</type>
      <value>fis-icon-chevron</value>
      <webElementGuid>034ecaf5-8884-4bd1-9105-155f1ee3456c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parentNode-Detailed&quot;)/mat-icon[@class=&quot;mat-icon notranslate icon fis-icon-sm fisfont fis-icon-chevron fis-icon-rotate-270 mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>e31bb685-9cf4-4219-8386-ac1fc2333346</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='parentNode-Detailed']/mat-icon</value>
      <webElementGuid>6bacaa9e-3c51-44b4-8e5a-71148fa788eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tree-node[4]/div/button/mat-icon</value>
      <webElementGuid>a79c1dad-d1bf-4b10-9871-e24483023475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
