<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Balance Sheet - Detailed_mat-mdc-butto_4daba1</name>
   <tag></tag>
   <elementGuidId>1dd29377-dc1b-4eb8-bce2-b681de74d45b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reportsPrintButton > span.mat-mdc-button-touch-target</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reportsPrintButton']/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#reportsPrintButton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6132646c-7856-4535-a5ff-6c9a4df763b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-button-touch-target</value>
      <webElementGuid>373f2447-bb7b-4d20-ae30-d6d76bb2414a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportsPrintButton&quot;)/span[@class=&quot;mat-mdc-button-touch-target&quot;]</value>
      <webElementGuid>4d2b9c5a-ba8a-4c69-955a-dbbf6a3049e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='reportsPrintButton']/span[3]</value>
      <webElementGuid>f6dffbdb-9ce1-43b1-9e56-4873cfee00ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/button/span[3]</value>
      <webElementGuid>6023d487-bd2a-4402-88ce-4f0bc485ece7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
