<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Print to PDF</name>
   <tag></tag>
   <elementGuidId>4d15f9a1-4653-49e1-8a87-1cd05608dfb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='menuButton']/span)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Print to PDF...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eac53be2-02ef-4519-8378-a1475099a5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-menu-item-text</value>
      <webElementGuid>c5da229a-fc65-49f4-8e0b-df832599a17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Print to PDF... </value>
      <webElementGuid>fa754b38-279f-47ff-8116-4bf4caba5f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-15&quot;)/div[@class=&quot;mat-mdc-menu-content ng-tns-c1923052698-91&quot;]/button[@id=&quot;menuButton&quot;]/span[@class=&quot;mat-mdc-menu-item-text&quot;]</value>
      <webElementGuid>cd81c1a2-f1af-4f18-a5db-5a797a7149a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='menuButton']/span)[3]</value>
      <webElementGuid>682af562-7af2-4903-9288-6026159a3f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print with Preview...'])[1]/following::span[1]</value>
      <webElementGuid>e3c9c94d-e7f9-4688-b1a6-47afc886ec46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print...'])[1]/following::span[2]</value>
      <webElementGuid>33e71864-4724-46e3-b7f3-9ecd10762a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Print to PDF...']/parent::*</value>
      <webElementGuid>93e47be4-e7d1-4f57-aab8-289cc43cae4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button[3]/span</value>
      <webElementGuid>5e1c1f35-b87d-4822-8ab0-5f6635ff9b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Print to PDF... ' or . = ' Print to PDF... ')]</value>
      <webElementGuid>7219e770-5664-4fe6-ba71-99263c93da40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
