<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Balance Sheet - Detailed</name>
   <tag></tag>
   <elementGuidId>dd8dab91-da19-4548-9657-8427ee09db27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-6a815149-ca1c-1dc1-0b8a-3a1a32fac40c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='-6a815149-ca1c-1dc1-0b8a-3a1a32fac40c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Balance Sheet - Detailed&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e1de6d60-7c2e-49bb-b072-36a87d3b66c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-6a815149-ca1c-1dc1-0b8a-3a1a32fac40c</value>
      <webElementGuid>6764c490-bbfd-4695-97b9-79bd8de7adf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>abfca42a-bea3-42ea-a1cb-9f1c68ef62b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Balance Sheet - Detailed </value>
      <webElementGuid>53797036-a42d-4e3b-b1c2-6b9893f816f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-6a815149-ca1c-1dc1-0b8a-3a1a32fac40c&quot;)</value>
      <webElementGuid>9a98678d-22d3-4291-b4e2-2514212d8682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='-6a815149-ca1c-1dc1-0b8a-3a1a32fac40c']</value>
      <webElementGuid>5b985355-4378-4fb2-9ff1-2ebfe9cac4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//opt-tree[@id='reportTree']/div/mat-radio-group/mat-tree/mat-tree-node[5]/div/span</value>
      <webElementGuid>119bec3b-8252-423e-9ce3-baef9f68d863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detailed'])[1]/following::span[1]</value>
      <webElementGuid>40b710fb-8910-41d8-9cf3-e98d769175fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Reports'])[1]/following::span[2]</value>
      <webElementGuid>28676053-e6bd-4a37-9bdf-5bbe04d09569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Income Sheet - Detailed'])[1]/preceding::span[1]</value>
      <webElementGuid>0f224956-167a-42ef-a11b-138b909e4aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Flow - Detailed'])[1]/preceding::span[2]</value>
      <webElementGuid>8ab11b09-22da-43e0-b6c4-c3b4991ab29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Balance Sheet - Detailed']/parent::*</value>
      <webElementGuid>f671207b-9737-44dc-a3e1-247504b484f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tree-node[5]/div/span</value>
      <webElementGuid>882328f1-d112-4518-85c2-9562343d62c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '-6a815149-ca1c-1dc1-0b8a-3a1a32fac40c' and (text() = ' Balance Sheet - Detailed ' or . = ' Balance Sheet - Detailed ')]</value>
      <webElementGuid>5de47053-01c0-475a-8862-f6fde579dc2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
