<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_General Reports_mat</name>
   <tag></tag>
   <elementGuidId>56ce4830-8d62-447b-bf3f-fe45a8b469c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parentNode-Detailed > mat-icon.mat-icon.notranslate.icon.fis-icon-sm.fisfont.fis-icon-chevron.fis-icon-rotate-270.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='parentNode-Detailed']/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#parentNode-Detailed</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>9d745478-c5e9-46e3-b593-2698fcc6d71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>73134268-f6a4-4b85-887f-947c04dc44f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fisicon</name>
      <type>Main</type>
      <value>chevron</value>
      <webElementGuid>e6b7c550-2d1f-4918-ad16-01a7225256d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ruficonstyle</name>
      <type>Main</type>
      <value>rotate-270</value>
      <webElementGuid>a98afd63-9a9c-4499-8e6b-f2462a760a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate icon fis-icon-sm fisfont fis-icon-chevron fis-icon-rotate-270 mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>ba692819-3a66-47cf-a35d-8bc79346660e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>efe5d223-b2d2-4468-a8d4-a9bdc01b9df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>f82c0f29-e6d4-4ecf-92bc-9527c3fe0551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>fis-icon-chevron</value>
      <webElementGuid>4150cd17-3b61-4526-980b-d954cb6dad3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-namespace</name>
      <type>Main</type>
      <value>fisfont</value>
      <webElementGuid>578f9655-d70d-4975-aa09-c23ae9472c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fonticon</name>
      <type>Main</type>
      <value>fis-icon-chevron</value>
      <webElementGuid>db8822b9-915c-448e-89b2-e69395f867fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parentNode-Detailed&quot;)/mat-icon[@class=&quot;mat-icon notranslate icon fis-icon-sm fisfont fis-icon-chevron fis-icon-rotate-270 mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>326f4ffc-cc86-4066-ba29-d7ed715e7b35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='parentNode-Detailed']/mat-icon</value>
      <webElementGuid>c7ac9b53-5295-4da9-9316-602228ef166d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tree-node[4]/div/button/mat-icon</value>
      <webElementGuid>2ceb6de6-fb97-48f3-a718-3de2c6bbf35e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
