<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Income Sheet - Detailed</name>
   <tag></tag>
   <elementGuidId>3be5eadc-5130-465a-9473-7cf5395bfe29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-90199109-f38b-439c-9adb-219bdaeb718c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='-90199109-f38b-439c-9adb-219bdaeb718c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Income Sheet - Detailed&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>60d630c5-394c-4b6e-8b13-760a720ca510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-90199109-f38b-439c-9adb-219bdaeb718c</value>
      <webElementGuid>8d28b909-ed44-4d61-9ce5-4acfec38a0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>c71d4e50-c53f-45ca-a55c-c5427508bbb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Income Sheet - Detailed </value>
      <webElementGuid>46b5e5b4-b898-4854-bb7e-a6af2aae62da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-90199109-f38b-439c-9adb-219bdaeb718c&quot;)</value>
      <webElementGuid>9d52afd6-3b7f-4371-a462-6b9fd6b7b82d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='-90199109-f38b-439c-9adb-219bdaeb718c']</value>
      <webElementGuid>e0ade471-9679-4545-96ae-dc17a643bfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//opt-tree[@id='reportTree']/div/mat-radio-group/mat-tree/mat-tree-node[6]/div/span</value>
      <webElementGuid>de25fa5b-15dc-44ba-ac81-ed301d400055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance Sheet - Detailed'])[1]/following::span[1]</value>
      <webElementGuid>5ee1d144-e18c-4842-9cdd-6447fb67b32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detailed'])[1]/following::span[2]</value>
      <webElementGuid>ddc10efa-34d1-4c25-a427-e297f996b7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Flow - Detailed'])[1]/preceding::span[1]</value>
      <webElementGuid>6ec3d934-e8d6-4c21-9d51-fbf0fafd0993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consolidated statement of changes - Detailed'])[1]/preceding::span[2]</value>
      <webElementGuid>afa10c0e-169d-4f29-b1da-001e38450d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Income Sheet - Detailed']/parent::*</value>
      <webElementGuid>f45eeafc-9d89-460b-a04a-465b302bdd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tree-node[6]/div/span</value>
      <webElementGuid>91c72483-7bd2-4f16-9544-6e1de1780fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '-90199109-f38b-439c-9adb-219bdaeb718c' and (text() = ' Income Sheet - Detailed ' or . = ' Income Sheet - Detailed ')]</value>
      <webElementGuid>ae7859fa-949a-4d62-80c1-7b0959aacf06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
