<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_01</name>
   <tag></tag>
   <elementGuidId>56580f38-0f55-4c43-a2d2-993e181e6deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mdc-list-item__primary-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='option-0296331e-c8f0-fcb9-96cc-3a1d37e07e51']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;01&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7da54446-a6db-4f50-b177-e3c9232abba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-list-item__primary-text</value>
      <webElementGuid>9869247e-2f19-48b1-b971-1f73acda30aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 01 </value>
      <webElementGuid>e206c609-89f2-4e8b-8d02-7d3c9b3b99ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-0296331e-c8f0-fcb9-96cc-3a1d37e07e51&quot;)/span[@class=&quot;mdc-list-item__primary-text&quot;]</value>
      <webElementGuid>b57c84b4-5a58-498c-8b72-9c0021005811</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='option-0296331e-c8f0-fcb9-96cc-3a1d37e07e51']/span</value>
      <webElementGuid>4773b2d5-5dd9-4a1d-8a4d-52880721f449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statement : 1 : 12/31/2021 (Historical)'])[1]/following::span[1]</value>
      <webElementGuid>63fb2111-ec8d-493c-b3e8-9b47ddc5a347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oil &amp; Gas Commercial Risk Template (4.0.0)'])[1]/following::span[1]</value>
      <webElementGuid>6f48860d-a937-4684-b173-8affe71ed8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='01']/parent::*</value>
      <webElementGuid>64f0b88f-8aee-4dba-974f-9521e86e84e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option/span</value>
      <webElementGuid>5d2d00f5-6139-4a84-b404-d7489724a144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' 01 ' or . = ' 01 ')]</value>
      <webElementGuid>0f3f4c16-56a1-45a4-ab4e-e02967dca035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
