<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_General</name>
   <tag></tag>
   <elementGuidId>0514ce2c-fc28-428e-981e-1ea8d6831c01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parentNode-Detailed > mat-icon.mat-icon.notranslate.icon.fis-icon-sm.fisfont.fis-icon-chevron.fis-icon-rotate-270.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='parentNode-Detailed']/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#parentNode-Detailed</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>95cf71fe-2432-4832-a3ab-87177e8a12fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>35e8f004-4837-4fe7-8c31-89db6af75fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fisicon</name>
      <type>Main</type>
      <value>chevron</value>
      <webElementGuid>5cd76aca-7bd7-4bdb-9b2f-6240ccd7915a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ruficonstyle</name>
      <type>Main</type>
      <value>rotate-270</value>
      <webElementGuid>9bdfa4ad-a2bf-44d2-8cb2-05ad343a949b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate icon fis-icon-sm fisfont fis-icon-chevron fis-icon-rotate-270 mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>fb4cdbc4-21f0-49ef-8e0c-b11211e1a12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bcb1d826-169f-4665-9c73-b2f98544a1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>370be320-e093-4d48-9ee8-6db1805f8f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>fis-icon-chevron</value>
      <webElementGuid>95952c4d-ed37-48ba-8f11-29f934c4fa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-namespace</name>
      <type>Main</type>
      <value>fisfont</value>
      <webElementGuid>003bb310-c2fc-4bd3-9f4f-b2b8c4e7dc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fonticon</name>
      <type>Main</type>
      <value>fis-icon-chevron</value>
      <webElementGuid>304db8d6-b364-46bc-89cd-e2a633a74bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parentNode-Detailed&quot;)/mat-icon[@class=&quot;mat-icon notranslate icon fis-icon-sm fisfont fis-icon-chevron fis-icon-rotate-270 mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>3219e13b-bbfb-4d83-b931-c2b0e6dc374c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='parentNode-Detailed']/mat-icon</value>
      <webElementGuid>8aa208d1-7055-4ace-aaec-fab15b375815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tree-node[4]/div/button/mat-icon</value>
      <webElementGuid>61755feb-4122-4bcb-9267-342b9448050c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
