<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ratios - Detailed</name>
   <tag></tag>
   <elementGuidId>9df79dd3-1b09-4340-94a5-ccb5c2278609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-60164a4c-39ba-410f-ab3f-c1b733e9f1ff</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='-60164a4c-39ba-410f-ab3f-c1b733e9f1ff']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Ratios - Detailed&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>749d61c6-3574-4a65-be11-40a9942f7aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-60164a4c-39ba-410f-ab3f-c1b733e9f1ff</value>
      <webElementGuid>04d12b0e-e833-4765-9cdd-6ea85eb5c818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>8c4f4f3e-49ce-43a1-8835-be8bb901f57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ratios - Detailed </value>
      <webElementGuid>0ab107fa-5691-4c13-b7e3-057530d35114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-60164a4c-39ba-410f-ab3f-c1b733e9f1ff&quot;)</value>
      <webElementGuid>a48b5716-03ce-4d54-a0fd-0b82cb997224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='-60164a4c-39ba-410f-ab3f-c1b733e9f1ff']</value>
      <webElementGuid>abe919cc-3af6-483c-a19d-d998bfdb2822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//opt-tree[@id='reportTree']/div/mat-radio-group/mat-tree/mat-tree-node[9]/div/span</value>
      <webElementGuid>71731b25-0f8d-4e18-8696-dde41e9fb574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consolidated statement of changes - Detailed'])[1]/following::span[1]</value>
      <webElementGuid>c9406fbd-bcdf-4fca-bfb9-632e0a267db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Flow - Detailed'])[1]/following::span[2]</value>
      <webElementGuid>a8224528-9ac4-47fc-9e23-7c425a56b9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Report Generated'])[1]/preceding::span[1]</value>
      <webElementGuid>c54aac24-da81-4ad4-aaa1-81274961c5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[1]</value>
      <webElementGuid>1f9e7d1e-1f7b-4545-b46e-76239523249b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ratios - Detailed']/parent::*</value>
      <webElementGuid>de258a9c-1dc4-4638-a8af-76765159b997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tree-node[9]/div/span</value>
      <webElementGuid>bbd98cef-1d46-455a-bd48-2c4d7dec6eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '-60164a4c-39ba-410f-ab3f-c1b733e9f1ff' and (text() = ' Ratios - Detailed ' or . = ' Ratios - Detailed ')]</value>
      <webElementGuid>1cf4a21e-f625-452c-b7ec-aa4aebb7571b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
