<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_General Report</name>
   <tag></tag>
   <elementGuidId>16bfc879-7457-4447-9af9-4c923d8cbad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parentNode-Detailed > mat-icon.mat-icon.notranslate.icon.fis-icon-sm.fisfont.fis-icon-chevron.fis-icon-rotate-270.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='parentNode-Detailed']/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#parentNode-Detailed</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>1df9dd34-224e-4be9-9697-5255657356a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>9d2ed858-b18a-4efe-ba65-7073c72e1f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fisicon</name>
      <type>Main</type>
      <value>chevron</value>
      <webElementGuid>1e497dbe-012b-4efc-86d0-392924cedcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ruficonstyle</name>
      <type>Main</type>
      <value>rotate-270</value>
      <webElementGuid>91c04997-612a-4108-92b0-7a4b745d8a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate icon fis-icon-sm fisfont fis-icon-chevron fis-icon-rotate-270 mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>8abf61dc-a667-4a29-a785-260e2b0166b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad0f3276-dd09-42c9-b8a4-15d82e40d2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>bcadade3-b1db-48a0-9f15-f1e2faa7b977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>fis-icon-chevron</value>
      <webElementGuid>b2f39095-7db5-4c6c-9f22-958ec1e63a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-namespace</name>
      <type>Main</type>
      <value>fisfont</value>
      <webElementGuid>a43c9d6f-cb4d-4119-ad32-0447e046285c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fonticon</name>
      <type>Main</type>
      <value>fis-icon-chevron</value>
      <webElementGuid>b9e0f827-badd-4a9b-979b-3bda460f6115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parentNode-Detailed&quot;)/mat-icon[@class=&quot;mat-icon notranslate icon fis-icon-sm fisfont fis-icon-chevron fis-icon-rotate-270 mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>f7b2fbc2-53b9-4508-9c4e-735f323bd671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='parentNode-Detailed']/mat-icon</value>
      <webElementGuid>49c6c130-551e-4eb4-a803-9ffc7499887b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tree-node[4]/div/button/mat-icon</value>
      <webElementGuid>1d0b78a3-6fdf-4a52-b584-1a2e0a1f78da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
