<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Consolidated statement of changes - Detailed</name>
   <tag></tag>
   <elementGuidId>4bf7946f-29fd-4655-8d59-2a31320b8d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-89a41e42-2ff9-4ae0-8fd3-7e2c623d3c65</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='-89a41e42-2ff9-4ae0-8fd3-7e2c623d3c65']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Consolidated statement of changes - Detailed&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f2156a0-384b-4967-807c-8be2dabbae93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-89a41e42-2ff9-4ae0-8fd3-7e2c623d3c65</value>
      <webElementGuid>45e481cd-e0ac-4d92-a36f-c528bd26ba71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>01fd755c-1b94-4e84-82f7-36243a4c442d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Consolidated statement of changes - Detailed </value>
      <webElementGuid>2bcf6fe7-0a84-45b6-b30f-1e8585c51060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-89a41e42-2ff9-4ae0-8fd3-7e2c623d3c65&quot;)</value>
      <webElementGuid>e6262d4d-0222-4d8f-9590-c91e8602373e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='-89a41e42-2ff9-4ae0-8fd3-7e2c623d3c65']</value>
      <webElementGuid>f49a1682-3020-4e70-8d3c-8411faae0e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//opt-tree[@id='reportTree']/div/mat-radio-group/mat-tree/mat-tree-node[8]/div/span</value>
      <webElementGuid>72e97323-0eaa-4fb1-83f0-e17f6b4b82f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Flow - Detailed'])[1]/following::span[1]</value>
      <webElementGuid>5950a139-e2ff-4739-9e7c-97c43595fb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Income Sheet - Detailed'])[1]/following::span[2]</value>
      <webElementGuid>7543613f-e393-4fc8-ae2f-5bc2a8e8f315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ratios - Detailed'])[1]/preceding::span[1]</value>
      <webElementGuid>59a0449a-d3f3-496d-8567-0b509ef8e59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Report Generated'])[1]/preceding::span[2]</value>
      <webElementGuid>75395cb5-51d6-4828-8d69-62be9255a731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Consolidated statement of changes - Detailed']/parent::*</value>
      <webElementGuid>0635231e-1d63-4f9a-b268-3c074603f2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tree-node[8]/div/span</value>
      <webElementGuid>1f442bf9-9645-4df1-9e26-4748426532c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '-89a41e42-2ff9-4ae0-8fd3-7e2c623d3c65' and (text() = ' Consolidated statement of changes - Detailed ' or . = ' Consolidated statement of changes - Detailed ')]</value>
      <webElementGuid>68f7503d-3dcd-4aca-b2b6-d0ec325cb7a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
