<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Print</name>
   <tag></tag>
   <elementGuidId>7abff708-9a3c-43e8-836c-0e6184cc58a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-mdc-menu-item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menuButton']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Print...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d8fe6038-932a-4b5a-8faa-0345e30ae877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-menu-item-text</value>
      <webElementGuid>0868484b-8354-43c8-b141-d71cf5a2a950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Print... </value>
      <webElementGuid>23023888-239e-4a63-b9f1-53f1a68c7845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-2&quot;)/div[@class=&quot;mat-mdc-menu-content ng-tns-c1923052698-11&quot;]/button[@id=&quot;menuButton&quot;]/span[@class=&quot;mat-mdc-menu-item-text&quot;]</value>
      <webElementGuid>e123689d-f3c3-4c4e-8efa-702f67275949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='menuButton']/span</value>
      <webElementGuid>98cb40bc-297a-42f8-a585-a030daddc6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set the report layout to landscape'])[1]/following::span[1]</value>
      <webElementGuid>f611883a-a7f8-4d30-887c-a1e4fb0bbebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::span[1]</value>
      <webElementGuid>140c2299-4679-4814-9a89-e5bd14e0207a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print with Preview...'])[1]/preceding::span[1]</value>
      <webElementGuid>8040f5d3-8c73-4bce-85e6-448d5c16d969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print to PDF...'])[1]/preceding::span[2]</value>
      <webElementGuid>b3c41486-f341-49b2-b06f-5ad717a11bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Print...']/parent::*</value>
      <webElementGuid>621fc5f6-4542-4098-a67b-14871a96c91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button/span</value>
      <webElementGuid>c5a97018-ff9f-4ea7-a4b4-9b675aae4fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Print... ' or . = ' Print... ')]</value>
      <webElementGuid>9bc59f90-9149-43da-bdfb-8367c7304c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
