<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_My Views (0)_filter-text-box</name>
   <tag></tag>
   <elementGuidId>be28fc89-c9f9-48ad-93fb-d1fd7fe8bb37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-text-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-text-box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search Customers&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>054efb75-859c-4c42-8703-46ad2ee96d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-text-box</value>
      <webElementGuid>516e8c37-d47a-4eb1-8f4b-564befc18d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSearchVal</value>
      <webElementGuid>8c698942-2311-4917-9d8f-a9137457fd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>floatplaceholder</name>
      <type>Main</type>
      <value>never</value>
      <webElementGuid>7d495c52-315e-48ab-9013-7c43f82251c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4dd2b9ea-63a8-491b-8991-2d13ab08b005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element ng-tns-c1534922977-1 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored</value>
      <webElementGuid>5de81e3c-3f96-45fb-a51e-d2010c76cf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Customers</value>
      <webElementGuid>46699e28-b719-4dbd-bf31-23bb432879f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>65a281cb-8237-4264-9873-0602961f886f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d09678db-024f-46cd-a04b-903e28ddbda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-text-box&quot;)</value>
      <webElementGuid>c246bf25-6e3b-409a-bbeb-c68c88d2fd52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-text-box']</value>
      <webElementGuid>dfbd6eb2-3602-4cbe-ac2a-f7a29bb57187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchAllBox']/mat-form-field/div/div/div[2]/input</value>
      <webElementGuid>c3ece0b6-76e2-4d86-a0af-d908aea1acf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f032ea9d-deb5-4c64-a26b-12cb4d4ac837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-text-box' and @name = 'txtSearchVal' and @placeholder = 'Search Customers']</value>
      <webElementGuid>99fc6e87-4490-43d8-b69c-3b608a6dea47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
