<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_</name>
   <tag></tag>
   <elementGuidId>78738843-4782-4966-9509-0a1c289b46e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parentNode-Detailed > mat-icon.mat-icon.notranslate.icon.fis-icon-sm.fisfont.fis-icon-chevron.fis-icon-rotate-270.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='parentNode-Detailed']/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#parentNode-Detailed</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>2a933bc2-ca5a-4ad0-bc30-ed3dddcfb6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>dbe02ad1-4a94-4f2c-ac49-29fe2a18c673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fisicon</name>
      <type>Main</type>
      <value>chevron</value>
      <webElementGuid>3d2e66c1-8354-41d4-80f5-53a49b91f667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ruficonstyle</name>
      <type>Main</type>
      <value>rotate-270</value>
      <webElementGuid>1ed3950c-2ca6-4147-94f2-8b23c89de255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate icon fis-icon-sm fisfont fis-icon-chevron fis-icon-rotate-270 mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>31139003-780b-42d2-a21d-e0bbbc1142c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9724d195-ed18-4d92-96e5-0719ec29de9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>e8acb29c-5552-4401-b5f9-41f70aabe79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>fis-icon-chevron</value>
      <webElementGuid>3dfe4bf8-5a7b-4578-9058-53a139bca112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-namespace</name>
      <type>Main</type>
      <value>fisfont</value>
      <webElementGuid>e839d079-7e5c-4886-9095-2a4d7e199e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fonticon</name>
      <type>Main</type>
      <value>fis-icon-chevron</value>
      <webElementGuid>6c4113cb-27fb-4ab6-a343-5c20dd524915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parentNode-Detailed&quot;)/mat-icon[@class=&quot;mat-icon notranslate icon fis-icon-sm fisfont fis-icon-chevron fis-icon-rotate-270 mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>c68e57e0-1f00-4526-b5c2-3f1d3aca3c79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='parentNode-Detailed']/mat-icon</value>
      <webElementGuid>97f05803-f176-439d-ade2-749aec79a46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tree-node[4]/div/button/mat-icon</value>
      <webElementGuid>0179510b-9545-4fc3-a450-a2a3f95bbea2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
