<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cash Flow - Detailed</name>
   <tag></tag>
   <elementGuidId>05c52900-0e8e-4e59-8cff-104351ac48c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-92896448-34ff-48de-860e-37fd316452cd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='-92896448-34ff-48de-860e-37fd316452cd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Cash Flow - Detailed&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6ec6962f-12df-4090-94e5-3a945cbad56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-92896448-34ff-48de-860e-37fd316452cd</value>
      <webElementGuid>e20c8f54-980e-4f96-8c6e-6366239c422a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>5683cd34-0df7-44a8-bcb8-d2017e0429eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cash Flow - Detailed </value>
      <webElementGuid>55084732-47f7-4287-b595-8ca1fa0f68dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-92896448-34ff-48de-860e-37fd316452cd&quot;)</value>
      <webElementGuid>5373c701-7690-41db-a8e1-4316daf7eacc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='-92896448-34ff-48de-860e-37fd316452cd']</value>
      <webElementGuid>e9fe55b0-34e1-47e1-8f67-f4b6908830e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//opt-tree[@id='reportTree']/div/mat-radio-group/mat-tree/mat-tree-node[7]/div/span</value>
      <webElementGuid>a5db76f7-ba79-4ac3-9aca-c3136ddda5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Income Sheet - Detailed'])[1]/following::span[1]</value>
      <webElementGuid>394da472-372a-4dae-9768-f43cc7802db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance Sheet - Detailed'])[1]/following::span[2]</value>
      <webElementGuid>271cfd5a-50e2-46b2-bdc6-66103b7feebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consolidated statement of changes - Detailed'])[1]/preceding::span[1]</value>
      <webElementGuid>59492355-1cc1-4517-9be3-6af6e915dc83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ratios - Detailed'])[1]/preceding::span[2]</value>
      <webElementGuid>443d60f9-71bd-4024-82f9-10d8f73e2823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cash Flow - Detailed']/parent::*</value>
      <webElementGuid>2085cd2f-c2e9-41da-a46d-5e0ab266be20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tree-node[7]/div/span</value>
      <webElementGuid>531705c4-1881-4eca-af70-5c2d514420a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '-92896448-34ff-48de-860e-37fd316452cd' and (text() = ' Cash Flow - Detailed ' or . = ' Cash Flow - Detailed ')]</value>
      <webElementGuid>07d64da2-3cc0-46e6-86da-e35ebdbcbeec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
