<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Print</name>
   <tag></tag>
   <elementGuidId>0d4dcc35-7312-4307-adee-435fed2dff3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-mdc-menu-item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menuButton']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Print...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6ec9838a-dffc-48c0-a7ae-fbe1b3fe6569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-menu-item-text</value>
      <webElementGuid>53f71aab-54c2-44c7-b228-08fb88a2592d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Print... </value>
      <webElementGuid>dc156dbd-9f22-4bed-9a87-a9d7f54c37fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-2&quot;)/div[@class=&quot;mat-mdc-menu-content ng-tns-c1923052698-11&quot;]/button[@id=&quot;menuButton&quot;]/span[@class=&quot;mat-mdc-menu-item-text&quot;]</value>
      <webElementGuid>834ee06d-aba5-407f-8032-a73eae35145c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='menuButton']/span</value>
      <webElementGuid>31b42ac7-f3ce-4b45-91db-d7de44823e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set the report layout to landscape'])[1]/following::span[1]</value>
      <webElementGuid>843248ed-bae6-499b-b2f7-f4569302f0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::span[1]</value>
      <webElementGuid>3114ffd2-682f-4c3c-9e99-9caf1c8c487c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print with Preview...'])[1]/preceding::span[1]</value>
      <webElementGuid>88daf69c-a3be-4917-8f7b-7cbaf88fd4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print to PDF...'])[1]/preceding::span[2]</value>
      <webElementGuid>4696b101-6f9b-40b0-a678-a2eaae068dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Print...']/parent::*</value>
      <webElementGuid>801b4635-e7ec-4cad-95ab-107f2de55814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button/span</value>
      <webElementGuid>4725e41c-8532-493e-b2f5-692ace94d807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Print... ' or . = ' Print... ')]</value>
      <webElementGuid>13e9be66-b7c2-4b31-a816-3cfd050fa176</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
