<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loan classification history across al_555b6f</name>
   <tag></tag>
   <elementGuidId>b3f8cab7-4ffd-453e-a305-bf047c9b64df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioOption_1_2_0-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radioOption_1_2_0-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Always open &amp; willing to cooperate&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb34474c-a399-4387-b9bd-6a35e20baf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7e868588-4bc2-4c3c-b1cf-84df0e98c8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-radio__native-control</value>
      <webElementGuid>4564c53f-14f0-41a8-b401-077905289ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioOption_1_2_0-input</value>
      <webElementGuid>4a023423-fbb8-4f78-a708-6a2879568ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mat-radio-group-3</value>
      <webElementGuid>529ed490-5b3c-4642-a728-5401c0cda384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c178aedc-b164-4cac-9ebf-b4b397ff589f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78c5574d-2da0-4f53-8485-506db3d13721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioOption_1_2_0-input&quot;)</value>
      <webElementGuid>3feb0e71-6e9d-4799-be32-f6d7d63b6a62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioOption_1_2_0-input']</value>
      <webElementGuid>0051d114-ab0a-49e8-b176-0f7402d12bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='radioOption_1_2_0']/div/div/input</value>
      <webElementGuid>a0feee12-6bdd-4e7b-8453-74daf33e9af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/opt-standard-scorecard-single-choice-question/div/mat-radio-group/mat-radio-button/div/div/input</value>
      <webElementGuid>50356d6f-9d9e-429a-8dff-2bf73a50b4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radioOption_1_2_0-input' and @name = 'mat-radio-group-3']</value>
      <webElementGuid>171d2723-6b14-4e70-bb8d-2158e381492e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
