<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ReluctantUnwilling to cooperate_radio_b8470a</name>
   <tag></tag>
   <elementGuidId>56e34398-2e26-4204-a35c-c7186fd18c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioOption_1_3_0-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radioOption_1_3_0-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;There is no history of default on debt payments at all banks, including BNI.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77154fb9-b350-43d9-95ea-41461a6a720c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d86b2048-af2c-4424-b134-2f9289fd953a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-radio__native-control</value>
      <webElementGuid>8efda3da-9465-4088-ace1-87a7768db45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioOption_1_3_0-input</value>
      <webElementGuid>7e2a2408-ab98-49e8-b1c4-dc202f902378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mat-radio-group-8</value>
      <webElementGuid>81a3fc67-2db8-4aef-b05d-77e4c9148c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>13736ead-6997-4d81-8061-ef069c8c2642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1d712be-9d1b-4626-a6a4-9a58464d1d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioOption_1_3_0-input&quot;)</value>
      <webElementGuid>ff2cb33b-3512-461a-a03a-1c357fd617f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioOption_1_3_0-input']</value>
      <webElementGuid>fdcacd9f-a3fb-4aad-8d37-5e4082e2101c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='radioOption_1_3_0']/div/div/input</value>
      <webElementGuid>3d6c210b-c708-4760-a2d3-bf08e6b6c3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/opt-standard-scorecard-single-choice-question/div/mat-radio-group/mat-radio-button/div/div/input</value>
      <webElementGuid>3cb3bf56-3a1a-49f2-ac15-4cd32764a848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radioOption_1_3_0-input' and @name = 'mat-radio-group-8']</value>
      <webElementGuid>d18a2189-7a9d-4b45-ae6d-7ab735305977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
