<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Qualitative Questions</name>
   <tag></tag>
   <elementGuidId>bd3301f2-98f3-4c9f-be26-607c226ddec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PageHeader_1']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PageHeader_1 > span.page-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Qualitative Questions&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8cefc138-d68f-4863-85a4-cef982815106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-name</value>
      <webElementGuid>d82ead0c-47b6-42fb-938e-2275547a4a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qualitative Questions</value>
      <webElementGuid>d0f6aab9-3f63-4fec-98c3-23d5fbdcc770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PageHeader_1&quot;)/span[@class=&quot;page-name&quot;]</value>
      <webElementGuid>e42851a5-96ec-4a10-af4f-8cd1ff467892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PageHeader_1']/span[2]</value>
      <webElementGuid>1119eee3-5284-4fa4-b000-e3456e458219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal Entity Details'])[1]/following::span[3]</value>
      <webElementGuid>ba3be0c3-532c-4058-a243-2bc45522a595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish'])[1]/following::span[7]</value>
      <webElementGuid>3d063fbc-49d3-48d1-918d-d9af54c672e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan classification history across all banks in the last two years.'])[1]/preceding::span[4]</value>
      <webElementGuid>4986be89-07b9-404a-a415-4e63be40daf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Always open &amp; willing to cooperate'])[1]/preceding::span[6]</value>
      <webElementGuid>dba46e41-108d-4b83-9003-02cca8831f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Qualitative Questions']/parent::*</value>
      <webElementGuid>08240f01-30ed-4b8a-adf6-193c0092b62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span[2]</value>
      <webElementGuid>2059a87d-35d3-48b4-bf9c-596299a3fa90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Qualitative Questions' or . = 'Qualitative Questions')]</value>
      <webElementGuid>6c4efe60-e9ae-45ad-b40c-6c9e39252422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
